#!/usr/bin/env python3
"""Generate additional Go standard library documentation entries.

Usage:
    uv run python src/scripts/generate_go_docs.py
"""

import json

from rich.console import Console

from src.config import GO_DOCS_FILE

console = Console()

NEW_DOCS = [
    # --- bufio ---
    {"package": "bufio", "api": "bufio.NewScanner(r io.Reader) *Scanner", "description": "Returns a new Scanner to read from r, splitting on lines by default.", "example": "scanner := bufio.NewScanner(os.Stdin)"},
    {"package": "bufio", "api": "scanner.Scan() bool", "description": "Advances the Scanner to the next token (line), returning false at EOF or error.", "example": "for scanner.Scan() { fmt.Println(scanner.Text()) }"},
    {"package": "bufio", "api": "scanner.Text() string", "description": "Returns the most recent token generated by a call to Scan as a string.", "example": "line := scanner.Text()"},
    {"package": "bufio", "api": "bufio.NewReader(rd io.Reader) *Reader", "description": "Returns a new Reader with default buffer size.", "example": "reader := bufio.NewReader(os.Stdin)"},
    {"package": "bufio", "api": "reader.ReadString(delim byte) (string, error)", "description": "Reads until the first occurrence of delim, returning the data including the delimiter.", "example": "line, _ := reader.ReadString('\\n')"},
    {"package": "bufio", "api": "bufio.NewWriter(w io.Writer) *Writer", "description": "Returns a new buffered Writer.", "example": "writer := bufio.NewWriter(os.Stdout); defer writer.Flush()"},

    # --- strconv ---
    {"package": "strconv", "api": "strconv.Atoi(s string) (int, error)", "description": "Converts a string to an int (base 10).", "example": "n, err := strconv.Atoi(\"42\")"},
    {"package": "strconv", "api": "strconv.Itoa(i int) string", "description": "Converts an int to its decimal string representation.", "example": "s := strconv.Itoa(42) // \"42\""},
    {"package": "strconv", "api": "strconv.ParseFloat(s string, bitSize int) (float64, error)", "description": "Converts a string to a floating-point number.", "example": "f, err := strconv.ParseFloat(\"3.14\", 64)"},
    {"package": "strconv", "api": "strconv.ParseInt(s string, base int, bitSize int) (int64, error)", "description": "Converts a string in the given base to an int64.", "example": "n, err := strconv.ParseInt(\"ff\", 16, 64) // 255"},
    {"package": "strconv", "api": "strconv.FormatFloat(f float64, fmt byte, prec, bitSize int) string", "description": "Converts a float64 to a string with given format and precision.", "example": "s := strconv.FormatFloat(3.14, 'f', 2, 64) // \"3.14\""},
    {"package": "strconv", "api": "strconv.FormatInt(i int64, base int) string", "description": "Returns the string representation of i in the given base.", "example": "s := strconv.FormatInt(255, 16) // \"ff\""},

    # --- sort ---
    {"package": "sort", "api": "sort.Ints(a []int)", "description": "Sorts a slice of ints in increasing order.", "example": "sort.Ints([]int{3, 1, 2}) // [1, 2, 3]"},
    {"package": "sort", "api": "sort.Strings(a []string)", "description": "Sorts a slice of strings in increasing order.", "example": "sort.Strings([]string{\"b\", \"a\"})"},
    {"package": "sort", "api": "sort.Slice(x any, less func(i, j int) bool)", "description": "Sorts slice x using the provided less function.", "example": "sort.Slice(s, func(i, j int) bool { return s[i] < s[j] })"},
    {"package": "sort", "api": "sort.SliceStable(x any, less func(i, j int) bool)", "description": "Stable sort of slice x using the provided less function.", "example": "sort.SliceStable(s, func(i, j int) bool { return s[i].Name < s[j].Name })"},
    {"package": "sort", "api": "sort.Search(n int, f func(int) bool) int", "description": "Binary search: returns the smallest index i in [0, n) at which f(i) is true.", "example": "i := sort.Search(len(a), func(i int) bool { return a[i] >= target })"},
    {"package": "sort", "api": "sort.SearchInts(a []int, x int) int", "description": "Binary search for x in sorted int slice a.", "example": "i := sort.SearchInts(a, 42)"},
    {"package": "sort", "api": "sort.Reverse(data sort.Interface) sort.Interface", "description": "Returns the reverse order for data.", "example": "sort.Sort(sort.Reverse(sort.IntSlice(s)))"},

    # --- math ---
    {"package": "math", "api": "math.Sqrt(x float64) float64", "description": "Returns the square root of x.", "example": "math.Sqrt(16) // 4.0"},
    {"package": "math", "api": "math.Pow(x, y float64) float64", "description": "Returns x raised to the power y.", "example": "math.Pow(2, 10) // 1024.0"},
    {"package": "math", "api": "math.Abs(x float64) float64", "description": "Returns the absolute value of x.", "example": "math.Abs(-3.5) // 3.5"},
    {"package": "math", "api": "math.Max(x, y float64) float64", "description": "Returns the larger of x or y.", "example": "math.Max(3.0, 5.0) // 5.0"},
    {"package": "math", "api": "math.Min(x, y float64) float64", "description": "Returns the smaller of x or y.", "example": "math.Min(3.0, 5.0) // 3.0"},
    {"package": "math", "api": "math.Ceil(x float64) float64", "description": "Returns the least integer value >= x.", "example": "math.Ceil(2.3) // 3.0"},
    {"package": "math", "api": "math.Floor(x float64) float64", "description": "Returns the greatest integer value <= x.", "example": "math.Floor(2.7) // 2.0"},
    {"package": "math", "api": "math.Log(x float64) float64", "description": "Returns the natural logarithm of x.", "example": "math.Log(math.E) // 1.0"},
    {"package": "math", "api": "math.Log2(x float64) float64", "description": "Returns the base-2 logarithm of x.", "example": "math.Log2(8) // 3.0"},
    {"package": "math", "api": "math.Inf(sign int) float64", "description": "Returns positive or negative infinity.", "example": "math.Inf(1) // +Inf"},
    {"package": "math", "api": "math.IsNaN(f float64) bool", "description": "Reports whether f is an IEEE 754 NaN.", "example": "math.IsNaN(math.NaN()) // true"},
    {"package": "math", "api": "math.Round(x float64) float64", "description": "Returns the nearest integer, rounding half away from zero.", "example": "math.Round(2.5) // 3.0"},
    {"package": "math", "api": "math.Mod(x, y float64) float64", "description": "Returns the floating-point remainder of x/y.", "example": "math.Mod(7, 3) // 1.0"},

    # --- sync ---
    {"package": "sync", "api": "sync.Mutex", "description": "A mutual exclusion lock. Lock() acquires, Unlock() releases.", "example": "var mu sync.Mutex; mu.Lock(); defer mu.Unlock()"},
    {"package": "sync", "api": "sync.WaitGroup", "description": "Waits for a collection of goroutines to finish. Add(n), Done(), Wait().", "example": "var wg sync.WaitGroup; wg.Add(1); go func() { defer wg.Done(); ... }(); wg.Wait()"},
    {"package": "sync", "api": "sync.Once", "description": "Ensures a function is executed only once.", "example": "var once sync.Once; once.Do(func() { initialize() })"},
    {"package": "sync", "api": "sync.Map", "description": "A concurrent-safe map. Store(k,v), Load(k), Delete(k), Range(f).", "example": "var m sync.Map; m.Store(\"key\", 42); v, ok := m.Load(\"key\")"},
    {"package": "sync", "api": "sync.RWMutex", "description": "Reader/writer mutual exclusion lock. RLock()/RUnlock() for reads, Lock()/Unlock() for writes.", "example": "var rw sync.RWMutex; rw.RLock(); defer rw.RUnlock()"},

    # --- context ---
    {"package": "context", "api": "context.Background() context.Context", "description": "Returns a non-nil, empty Context; typically used as the top-level Context.", "example": "ctx := context.Background()"},
    {"package": "context", "api": "context.WithCancel(parent Context) (Context, CancelFunc)", "description": "Returns a derived context that is canceled when cancel is called or parent is done.", "example": "ctx, cancel := context.WithCancel(context.Background()); defer cancel()"},
    {"package": "context", "api": "context.WithTimeout(parent Context, timeout time.Duration) (Context, CancelFunc)", "description": "Returns a derived context that is automatically canceled after the timeout.", "example": "ctx, cancel := context.WithTimeout(ctx, 5*time.Second); defer cancel()"},
    {"package": "context", "api": "context.WithValue(parent Context, key, val any) Context", "description": "Returns a derived context carrying the key-value pair.", "example": "ctx := context.WithValue(ctx, \"userID\", 42)"},

    # --- io ---
    {"package": "io", "api": "io.ReadAll(r Reader) ([]byte, error)", "description": "Reads from r until EOF and returns the data.", "example": "body, err := io.ReadAll(resp.Body)"},
    {"package": "io", "api": "io.Copy(dst Writer, src Reader) (int64, error)", "description": "Copies from src to dst until EOF.", "example": "io.Copy(os.Stdout, resp.Body)"},
    {"package": "io", "api": "io.EOF", "description": "The error returned by Read when no more input is available.", "example": "if err == io.EOF { break }"},
    {"package": "io", "api": "io.Reader interface", "description": "Interface with Read(p []byte) (n int, err error). The fundamental read interface.", "example": "func process(r io.Reader) { ... }"},
    {"package": "io", "api": "io.Writer interface", "description": "Interface with Write(p []byte) (n int, err error). The fundamental write interface.", "example": "func output(w io.Writer) { fmt.Fprint(w, \"hello\") }"},

    # --- errors ---
    {"package": "errors", "api": "errors.New(text string) error", "description": "Returns a new error with the given text.", "example": "err := errors.New(\"something went wrong\")"},
    {"package": "errors", "api": "errors.Is(err, target error) bool", "description": "Reports whether any error in err's chain matches target.", "example": "if errors.Is(err, os.ErrNotExist) { ... }"},
    {"package": "errors", "api": "errors.As(err error, target any) bool", "description": "Finds the first error in err's chain that matches target type and sets target.", "example": "var pathErr *os.PathError; errors.As(err, &pathErr)"},
    {"package": "errors", "api": "errors.Unwrap(err error) error", "description": "Returns the result of calling the Unwrap method on err.", "example": "inner := errors.Unwrap(err)"},
    {"package": "errors", "api": "errors.Join(errs ...error) error", "description": "Returns an error that wraps the given errors.", "example": "err := errors.Join(err1, err2)"},
    {"package": "errors", "api": "fmt.Errorf(format string, a ...any) error", "description": "Formats an error string. Use %w to wrap an existing error.", "example": "err := fmt.Errorf(\"failed to open %s: %w\", name, err)"},

    # --- regexp ---
    {"package": "regexp", "api": "regexp.Compile(expr string) (*Regexp, error)", "description": "Parses a regular expression and returns a Regexp object.", "example": "re, err := regexp.Compile(`\\d+`)"},
    {"package": "regexp", "api": "regexp.MustCompile(str string) *Regexp", "description": "Like Compile but panics on error. Use for constant patterns.", "example": "re := regexp.MustCompile(`[a-z]+`)"},
    {"package": "regexp", "api": "re.MatchString(s string) bool", "description": "Reports whether the string s contains any match of the regexp.", "example": "re.MatchString(\"hello123\") // true"},
    {"package": "regexp", "api": "re.FindString(s string) string", "description": "Returns the first match of the regexp in s.", "example": "re.FindString(\"hello 42 world\") // \"42\""},
    {"package": "regexp", "api": "re.FindAllString(s string, n int) []string", "description": "Returns all matches of the regexp in s, up to n matches (-1 for all).", "example": "re.FindAllString(\"a1 b2 c3\", -1) // [\"1\", \"2\", \"3\"]"},
    {"package": "regexp", "api": "re.ReplaceAllString(src, repl string) string", "description": "Returns a copy of src with all matches replaced by repl.", "example": "re.ReplaceAllString(\"hello 42\", \"NUM\") // \"hello NUM\""},
    {"package": "regexp", "api": "re.FindStringSubmatch(s string) []string", "description": "Returns a slice of strings holding the match and captured groups.", "example": "re.FindStringSubmatch(\"2024-01-15\") // [\"2024-01-15\", \"2024\", \"01\", \"15\"]"},

    # --- unicode ---
    {"package": "unicode", "api": "unicode.IsDigit(r rune) bool", "description": "Reports whether rune r is a decimal digit.", "example": "unicode.IsDigit('9') // true"},
    {"package": "unicode", "api": "unicode.IsLetter(r rune) bool", "description": "Reports whether rune r is a letter.", "example": "unicode.IsLetter('A') // true"},
    {"package": "unicode", "api": "unicode.IsSpace(r rune) bool", "description": "Reports whether rune r is a whitespace character.", "example": "unicode.IsSpace(' ') // true"},
    {"package": "unicode", "api": "unicode.IsUpper(r rune) bool", "description": "Reports whether rune r is an uppercase letter.", "example": "unicode.IsUpper('A') // true"},
    {"package": "unicode", "api": "unicode.IsLower(r rune) bool", "description": "Reports whether rune r is a lowercase letter.", "example": "unicode.IsLower('a') // true"},
    {"package": "unicode", "api": "unicode.ToUpper(r rune) rune", "description": "Maps rune r to its uppercase equivalent.", "example": "unicode.ToUpper('a') // 'A'"},
    {"package": "unicode", "api": "unicode.ToLower(r rune) rune", "description": "Maps rune r to its lowercase equivalent.", "example": "unicode.ToLower('A') // 'a'"},
    {"package": "unicode/utf8", "api": "utf8.RuneCountInString(s string) int", "description": "Returns the number of runes (characters) in s.", "example": "utf8.RuneCountInString(\"Hello\") // 5"},

    # --- container/heap ---
    {"package": "container/heap", "api": "heap.Init(h heap.Interface)", "description": "Establishes the heap invariants. Must be called before Push/Pop.", "example": "heap.Init(&pq)"},
    {"package": "container/heap", "api": "heap.Push(h heap.Interface, x any)", "description": "Pushes element x onto the heap.", "example": "heap.Push(&pq, item)"},
    {"package": "container/heap", "api": "heap.Pop(h heap.Interface) any", "description": "Removes and returns the minimum element from the heap.", "example": "item := heap.Pop(&pq)"},
    {"package": "container/heap", "api": "heap.Fix(h heap.Interface, i int)", "description": "Re-establishes heap ordering after the element at index i has changed.", "example": "heap.Fix(&pq, 0)"},

    # --- container/list ---
    {"package": "container/list", "api": "list.New() *List", "description": "Returns an initialized doubly-linked list.", "example": "l := list.New()"},
    {"package": "container/list", "api": "l.PushBack(v any) *Element", "description": "Inserts a new element at the back of the list.", "example": "l.PushBack(42)"},
    {"package": "container/list", "api": "l.PushFront(v any) *Element", "description": "Inserts a new element at the front of the list.", "example": "l.PushFront(1)"},
    {"package": "container/list", "api": "l.Remove(e *Element) any", "description": "Removes e from the list and returns its value.", "example": "l.Remove(elem)"},
    {"package": "container/list", "api": "l.Front() *Element", "description": "Returns the first element of the list.", "example": "front := l.Front()"},
    {"package": "container/list", "api": "l.Len() int", "description": "Returns the number of elements in the list.", "example": "n := l.Len()"},

    # --- math/big ---
    {"package": "math/big", "api": "big.NewInt(x int64) *Int", "description": "Creates a new big.Int initialized to x.", "example": "n := big.NewInt(42)"},
    {"package": "math/big", "api": "z.Add(x, y *Int) *Int", "description": "Sets z to x + y and returns z.", "example": "z := new(big.Int).Add(x, y)"},
    {"package": "math/big", "api": "z.Mul(x, y *Int) *Int", "description": "Sets z to x * y and returns z.", "example": "z := new(big.Int).Mul(x, y)"},
    {"package": "math/big", "api": "z.SetString(s string, base int) (*Int, bool)", "description": "Sets z to the value of s in the given base.", "example": "n, ok := new(big.Int).SetString(\"12345678901234567890\", 10)"},
    {"package": "math/big", "api": "z.Cmp(y *Int) int", "description": "Compares x and y: -1 if x < y, 0 if x == y, +1 if x > y.", "example": "if x.Cmp(y) > 0 { fmt.Println(\"x is greater\") }"},
    {"package": "math/big", "api": "z.String() string", "description": "Returns the decimal string representation of z.", "example": "fmt.Println(n.String())"},

    # --- slices (Go 1.21+) ---
    {"package": "slices", "api": "slices.Contains(s []T, v T) bool", "description": "Reports whether v is present in s.", "example": "slices.Contains([]int{1, 2, 3}, 2) // true"},
    {"package": "slices", "api": "slices.Index(s []T, v T) int", "description": "Returns the index of the first occurrence of v in s, or -1.", "example": "slices.Index([]string{\"a\", \"b\"}, \"b\") // 1"},
    {"package": "slices", "api": "slices.Reverse(s []T)", "description": "Reverses the elements of the slice in place.", "example": "slices.Reverse(s)"},
    {"package": "slices", "api": "slices.Sort(x []T)", "description": "Sorts a slice of ordered types in ascending order.", "example": "slices.Sort([]int{3, 1, 2}) // [1, 2, 3]"},
    {"package": "slices", "api": "slices.Max(x []T) T", "description": "Returns the maximal value in x.", "example": "slices.Max([]int{1, 5, 3}) // 5"},
    {"package": "slices", "api": "slices.Min(x []T) T", "description": "Returns the minimal value in x.", "example": "slices.Min([]int{1, 5, 3}) // 1"},

    # --- maps (Go 1.21+) ---
    {"package": "maps", "api": "maps.Keys(m map[K]V) []K", "description": "Returns a slice of all keys in the map.", "example": "keys := maps.Keys(m)"},
    {"package": "maps", "api": "maps.Values(m map[K]V) []V", "description": "Returns a slice of all values in the map.", "example": "vals := maps.Values(m)"},
    {"package": "maps", "api": "maps.Clone(m map[K]V) map[K]V", "description": "Returns a shallow copy of the map.", "example": "m2 := maps.Clone(m)"},

    # --- strings (additional) ---
    {"package": "strings", "api": "strings.Contains(s, substr string) bool", "description": "Reports whether substr is within s.", "example": "strings.Contains(\"seafood\", \"foo\") // true"},
    {"package": "strings", "api": "strings.Repeat(s string, count int) string", "description": "Returns a new string consisting of count copies of s.", "example": "strings.Repeat(\"na\", 3) // \"nanana\""},
    {"package": "strings", "api": "strings.NewReader(s string) *Reader", "description": "Returns a new Reader reading from s. Implements io.Reader.", "example": "r := strings.NewReader(\"hello\")"},
    {"package": "strings", "api": "strings.TrimLeft(s, cutset string) string", "description": "Returns s with all leading characters in cutset removed.", "example": "strings.TrimLeft(\"¡¡¡Hello\", \"!¡\") // \"Hello\""},
    {"package": "strings", "api": "strings.TrimRight(s, cutset string) string", "description": "Returns s with all trailing characters in cutset removed.", "example": "strings.TrimRight(\"Hello!!!\", \"!\") // \"Hello\""},
    {"package": "strings", "api": "strings.Fields(s string) []string", "description": "Splits s around whitespace, returning a slice of substrings.", "example": "strings.Fields(\"  a  b  c  \") // [\"a\", \"b\", \"c\"]"},
    {"package": "strings", "api": "strings.Map(mapping func(rune) rune, s string) string", "description": "Returns a copy of s with each rune mapped by the function.", "example": "strings.Map(unicode.ToUpper, \"hello\") // \"HELLO\""},

    # --- fmt (additional) ---
    {"package": "fmt", "api": "fmt.Scanf(format string, a ...any) (int, error)", "description": "Scans text read from stdin according to a format string.", "example": "fmt.Scanf(\"%d %d\", &a, &b)"},
    {"package": "fmt", "api": "fmt.Sscanf(str string, format string, a ...any) (int, error)", "description": "Scans a string according to a format.", "example": "fmt.Sscanf(\"42 3.14\", \"%d %f\", &n, &f)"},
    {"package": "fmt", "api": "fmt.Sprint(a ...any) string", "description": "Formats using default formats and returns the resulting string.", "example": "s := fmt.Sprint(42) // \"42\""},
    {"package": "fmt", "api": "fmt.Fprintf(w io.Writer, format string, a ...any) (int, error)", "description": "Formats and writes to w.", "example": "fmt.Fprintf(os.Stderr, \"error: %v\\n\", err)"},
]


def main():
    console.print("[bold]Generating additional Go documentation entries...[/bold]")

    # Load existing docs to check for duplicates
    existing_apis = set()
    if GO_DOCS_FILE.exists():
        with open(GO_DOCS_FILE, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    r = json.loads(line)
                    existing_apis.add(r["api"])

    console.print(f"  Existing entries: {len(existing_apis)}")

    # Filter out duplicates
    new_entries = [d for d in NEW_DOCS if d["api"] not in existing_apis]
    console.print(f"  New entries to add: {len(new_entries)}")

    if not new_entries:
        console.print("  [yellow]No new entries to add.[/yellow]")
        return

    # Append to file
    with open(GO_DOCS_FILE, "a", encoding="utf-8") as f:
        for entry in new_entries:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")

    total = len(existing_apis) + len(new_entries)
    console.print(f"  [green]Done![/green] Total entries: {total}")


if __name__ == "__main__":
    main()
